### PR TITLE
Update PTB version and other minor changes

### PR DESCRIPTION
**Pull request by ksdfg**
- bump up ptb dependency
- use the run_async parameter of Handler instead of decorator in basics.py
- use the run_async parameter of Handler instead of decorator in admin.py
- use the run_async parameter of Handler instead of decorator in exceptions.py
- use the run_async parameter of Handler instead of decorator in filter.py
- use the run_async parameter of Handler instead of decorator in memes.py
- use the run_async parameter of Handler instead of decorator in nhentai.py
- use the run_async parameter of Handler instead of decorator in notes.py
- use the run_async parameter of Handler instead of decorator in quote.py
- use the run_async parameter of Handler instead of decorator in stickers.py
- fix mute, unmute and ban/kick
- fix exceptions module reply messages
- update exceptions module commands
- stop the trigger from triggering to message trying to stop the trigger from triggering
- delete the command message when purging

### CODE REVIEW

**Comment by akhilnarang** [comment]
Seems okay mostly, but I wanna try something, will push a patch soon

**Comment by ksdfg** [comment]
@akhilnarang what do you wanna try?

**Comment by akhilnarang** [comment]
@ksdfg Merge it for now, I'll try what I had in mind later

**Comment by ksdfg** [comment]
@akhilnarang approve then bc, I changed settings so can't merge without minimum 1 approval

**Review by akhilnarang — APPROVED** [review]
Prusdfg

**Pull request merged**
